### ISSUE TITLE
Package subpath './v1' is not defined by "exports" in ..../flok/packages/core/node_modules/uuid/package.json

### ISSUE THREAD

**Issue by jwaldmann** [munshkr/flok#135]
Hi. I am getting this error:

```
node ./packages/web/bin/flok-web.js  -P 3000 -H localhost

internal/modules/cjs/loader.js:524
  throw new ERR_PACKAGE_PATH_NOT_EXPORTED(basePath, mappingKey);
  ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v1' is not defined by "exports" in /home/waldmann/software/music/flok/packages/core/node_modules/uuid/package.json
    at applyExports (internal/modules/cjs/loader.js:524:9)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:661:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:963:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/waldmann/software/music/flok/packages/core/lib/PubSub.js:8:30)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
```
A short web search turned up this similar thing (in an un-related project) https://github.com/sequelize/sequelize/issues/13123

**Comment by jwaldmann** [comment]
possibly a follow-up error because I was using node-v17.4.0. 

compilation works with v16.13.1

**Comment by munshkr** [comment]
Yes, I'm having a lot of issues with nextjs and the packaged bundle, still haven't figured out if I'm doing it wrong. The safest way to get to the latest version of the source code right now is to clone the repo and build it there, instead of relying on the published package on npm.

**Comment by jwaldmann** [comment]
But I was getting this error when buliding from `main` branch. What is the commit/tag that you recommend? I want #133, this is not in v0.4.5? Perhaps I can cherry-pick #133 onto v0.4.5

**Comment by munshkr** [comment]
Ah that's weird, then maybe we're talkimg about two different bugs... Maybe it is related to node version. Will check this later today and report.

**Comment by deadlyicon** [comment]
```js
import { v1 as uuid } from 'uuid'
```

worked for me
