### ISSUE TITLE
500 internal error running local flok-web

### ISSUE THREAD

**Issue by hjhinton** [munshkr/flok#155]
I saw a few other problems that appear to have been closed as they were marked closed + fixed, but with the most recent npm install appears to still be an issue:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at NextNodeServer.getEdgeFunctions (C:\Users\Henry\AppData\Roaming\nvm\v19.0.0\node_modules\flok-web\node_modules\next\dist\server\next-server.js:1011:23)
    at NextNodeServer.renderPageComponent (C:\Users\Henry\AppData\Roaming\nvm\v19.0.0\node_modules\flok-web\node_modules\next\dist\server\next-server.js:517:36)
    at NextNodeServer.renderToResponse (C:\Users\Henry\AppData\Roaming\nvm\v19.0.0\node_modules\flok-web\node_modules\next\dist\server\base-server.js:938:43)
    at pipe.req.req (C:\Users\Henry\AppData\Roaming\nvm\v19.0.0\node_modules\flok-web\node_modules\next\dist\server\base-server.js:445:38)
    at NextNodeServer.pipe (C:\Users\Henry\AppData\Roaming\nvm\v19.0.0\node_modules\flok-web\node_modules\next\dist\server\base-server.js:387:31)
    at NextNodeServer.render (C:\Users\Henry\AppData\Roaming\nvm\v19.0.0\node_modules\flok-web\node_modules\next\dist\server\base-server.js:445:21)
    at NextNodeServer.render (C:\Users\Henry\AppData\Roaming\nvm\v19.0.0\node_modules\flok-web\node_modules\next\dist\server\next-server.js:843:22)
    at Object.fn (C:\Users\Henry\AppData\Roaming\nvm\v19.0.0\node_modules\flok-web\node_modules\next\dist\server\next-server.js:749:32)
    at Object.fn (C:\Users\Henry\AppData\Roaming\nvm\v19.0.0\node_modules\flok-web\node_modules\next\dist\server\router.js:109:55)
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at NextNodeServer.getEdgeFunctions (C:\Users\Henry\AppData\Roaming\nvm\v19.0.0\node_modules\flok-web\node_modules\next\dist\server\next-server.js:1011:23)
    at NextNodeServer.renderPageComponent (C:\Users\Henry\AppData\Roaming\nvm\v19.0.0\node_modules\flok-web\node_modules\next\dist\server\next-server.js:517:36)
    at NextNodeServer.renderToResponse (C:\Users\Henry\AppData\Roaming\nvm\v19.0.0\node_modules\flok-web\node_modules\next\dist\server\base-server.js:938:43)
    at pipe.req.req (C:\Users\Henry\AppData\Roaming\nvm\v19.0.0\node_modules\flok-web\node_modules\next\dist\server\base-server.js:445:38)
    at NextNodeServer.pipe (C:\Users\Henry\AppData\Roaming\nvm\v19.0.0\node_modules\flok-web\node_modules\next\dist\server\base-server.js:387:31)
    at NextNodeServer.render (C:\Users\Henry\AppData\Roaming\nvm\v19.0.0\node_modules\flok-web\node_modules\next\dist\server\base-server.js:445:21)
    at NextNodeServer.render (C:\Users\Henry\AppData\Roaming\nvm\v19.0.0\node_modules\flok-web\node_modules\next\dist\server\next-server.js:843:22)
    at Object.fn (C:\Users\Henry\AppData\Roaming\nvm\v19.0.0\node_modules\flok-web\node_modules\next\dist\server\next-server.js:749:32)
    at Router.execute (C:\Users\Henry\AppData\Roaming\nvm\v19.0.0\node_modules\flok-web\node_modules\next\dist\server\router.js:252:48)

```

**Comment by yaxu** [comment]
I'm getting this under linux too:
```
alex@slab:~/src/flok$ flok-web -P 3030
> Server listening on 0.0.0.0, port 3030
> Visit http://92.205.63.123:3030
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at NextNodeServer.getEdgeFunctions (/home/alex/local/node/lib/node_modules/flok-web/node_modules/next/dist/server/next-server.js:1011:23)
    at NextNodeServer.renderPageComponent (/home/alex/local/node/lib/node_modules/flok-web/node_modules/next/dist/server/next-server.js:517:36)
    at NextNodeServer.renderToResponse (/home/alex/local/node/lib/node_modules/flok-web/node_modules/next/dist/server/base-server.js:938:43)
    at pipe.req.req (/home/alex/local/node/lib/node_modules/flok-web/node_modules/next/dist/server/base-server.js:445:38)
    at NextNodeServer.pipe (/home/alex/local/node/lib/node_modules/flok-web/node_modules/next/dist/server/base-server.js:387:31)
    at NextNodeServer.render (/home/alex/local/node/lib/node_modules/flok-web/node_modules/next/dist/server/base-server.js:445:21)
    at NextNodeServer.render (/home/alex/local/node/lib/node_modules/flok-web/node_modules/next/dist/server/next-server.js:843:22)
    at Object.fn (/home/alex/local/node/lib/node_modules/flok-web/node_modules/next/dist/server/next-server.js:749:32)
    at Router.execute (/home/alex/local/node/lib/node_modules/flok-web/node_modules/next/dist/server/router.js:252:48)
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at NextNodeServer.getEdgeFunctions (/home/alex/local/node/lib/node_modules/flok-web/node_modules/next/dist/server/next-server.js:1011:23)
    at NextNodeServer.renderPageComponent (/home/alex/local/node/lib/node_modules/flok-web/node_modules/next/dist/server/next-server.js:517:36)
    at NextNodeServer.renderToResponse (/home/alex/local/node/lib/node_modules/flok-web/node_modules/next/dist/server/base-server.js:938:43)
    at pipe.req.req (/home/alex/local/node/lib/node_modules/flok-web/node_modules/next/dist/server/base-server.js:445:38)
    at NextNodeServer.pipe (/home/alex/local/node/lib/node_modules/flok-web/node_modules/next/dist/server/base-server.js:387:31)
    at NextNodeServer.render (/home/alex/local/node/lib/node_modules/flok-web/node_modules/next/dist/server/base-server.js:445:21)
    at NextNodeServer.render (/home/alex/local/node/lib/node_modules/flok-web/node_modules/next/dist/server/next-server.js:843:22)
    at Object.fn (/home/alex/local/node/lib/node_modules/flok-web/node_modules/next/dist/server/next-server.js:749:32)
    at Router.execute (/home/alex/local/node/lib/node_modules/flok-web/node_modules/next/dist/server/router.js:252:48)
```

**Comment by yaxu** [comment]
Thanks @munshkr . This got it running, but we had problems with not seeing each others code edits despite it working otherwise in terms of code being sent to tidal. We switched to using the clic flok instead and that worked great though!

**Comment by munshkr** [comment]
> Thanks @munshkr . This got it running, but we had problems with not seeing each others code edits despite it working otherwise in terms of code being sent to tidal. We switched to using the clic flok instead and that worked great though!

Great! Sounds like the WebRTC connection didn't quite work (the code evaluations go through Websockets always), this happens sometimes because of NAT/router issues. The flok instance on https://flok.clic.cf/ is using a custom STUN/TURN server running there, which tries to solve those cases. Glad to see it worked!

**Comment by alvarocaceresmunoz** [comment]
I confirm this is happening at the moment with flok.cc (flock.clic.cf seems to be unavailable). We tried:
1. On PC1 (Windows), run flok-repl and Tidal
2. On PC1, open flok.cc on Firefox and create a session url
3. On PC2 (Mac), open the url. It gets a 500
5. On PC1, reload. It gets a 500 too

**Comment by alvarocaceresmunoz** [comment]
It happens even with a single Windows PC. I can create a session and join, but if I reload the page I get a 500

**Comment by yaxu** [comment]
Yes I have the same here under linux / chrome

**Comment by munshkr** [comment]
I think you all already are aware of the next-gen version of Flok (v1.0), this is already fixed there. Hope to release it soon!

**Comment by yaxu** [comment]
Yes flok-next works great !!
